name: "Terraform CI/CD Pipeline"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  id-token: write # Required for OIDC authentication
  contents: read
  pull-requests: write # Allows commenting the plan on PRs

jobs:
  terraform:
    name: "Terraform Lifecycle"
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository down to the GitHub runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Authenticate securely to AWS via OIDC (No keys stored!)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::907739325292:role/github-actions-tf-provisioner
          aws-region: us-east-1

      # 3. Install the specific version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0" # Lock this down to prevent drift

      # 4. Enforce Senior Guardrails: Formatting and Validation
      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # 5. Generate execution plan on Pull Requests
      - name: Terraform Plan
        #if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true

      # 6. Post the plan to the PR so team members can review it inline
      - name: Post Plan to Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `#### TF Format Check: Passed 🖌
            #### TF Initialization: Success ⚙️
            #### TF Validation: Success 🤖
            #### Plan Execution Output 🚀
            
            *Pushed by: @${context.actor}, Action: \`${context.eventName}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # Fail the job if the plan step failed, preventing unintended applies
      - name: Evaluate Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # 7. Apply the EXACT plan generated if merged into main
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
